# SQL Server Installation Configuration - SAMPLE FILE
# Copy this file to sql-server-config.yaml and customize for your environment

# FTP Credentials for ISO download
ftp:
  url: "ftp://your-ftp-server.com/path/to/SQLServer2022-x64-ENU-Dev.iso"
  username: "your-ftp-username"
  password: "your-ftp-password"
  iso_name: "SQLServer2022-x64-ENU-Dev.iso"

# Paths and SQL Server settings
paths:
  root: "F:"  # Change to your preferred drive/path
  version: "2022"
  instance_name: "MSSQLSERVER"

# Installation options
install_options:
  install_ssms: true
  install_ola: true
  install_whoisactive: true
  install_frk: true

# SQL Server configuration
sql_config:
  percent_max_memory: 75
  tempdb_data_files: "auto"  # Will use processor count
  tempdb_data_file_size_mb: 512
  tempdb_log_file_size_mb: 512

# Ola Hallengren job schedules
ola_schedules:
  user_databases:
    "DatabaseBackup - USER_DATABASES - FULL":
      schedule: "Daily 2AM"
      frequency_type: "Daily"
      start_time: "020000"
    
    "DatabaseBackup - USER_DATABASES - LOG":
      schedule: "Every 15 Minutes"
      frequency_type: "Daily"
      frequency_sub_day_type: "Minute"
      frequency_sub_day_interval: 15
      start_time: "000000"
    
    "DatabaseBackup - USER_DATABASES - DIFF":
      schedule: "Daily 6AM"
      frequency_type: "Daily"
      start_time: "060000"
    
    "DatabaseIntegrityCheck - USER_DATABASES":
      schedule: "Daily 1AM"
      frequency_type: "Daily"
      start_time: "010000"
    
    "IndexOptimize - USER_DATABASES":
      schedule: "Weekly Sunday 3AM"
      frequency_type: "Weekly"
      frequency_interval: "Sunday"
      start_time: "030000"
  
  system_databases:
    "DatabaseBackup - SYSTEM_DATABASES - FULL":
      schedule: "Daily 2:30AM"
      frequency_type: "Daily"
      start_time: "023000"
    
    "DatabaseIntegrityCheck - SYSTEM_DATABASES":
      schedule: "Weekly Sunday 4AM"
      frequency_type: "Weekly"
      frequency_interval: "Sunday"
      start_time: "040000"
  
  cleanup:
    "CommandLog Cleanup":
      schedule: "Daily Midnight"
      frequency_type: "Daily"
      start_time: "000000"
    
    "Output File Cleanup":
      schedule: "Daily Midnight"
      frequency_type: "Daily"
      start_time: "000000"
    
    "sp_delete_backuphistory":
      schedule: "Weekly Saturday 1AM"
      frequency_type: "Weekly"
      frequency_interval: "Saturday"
      start_time: "010000"
    
    "sp_purge_jobhistory":
      schedule: "Weekly Saturday 1:30AM"
      frequency_type: "Weekly"
      frequency_interval: "Saturday"
      start_time: "013000"
